version: "3"

services:
    selenium:
        image: selenium/standalone-chrome:3.141.59
        container_name: selenium_server
        ports:
            - "4444:4444"
        logging:
            driver: none

    text_box_test:
        build:
            context: /
            dockerfile: /
        container_name: text_box_test_container
        network_mode: "host"
